import sys # 导入sys模块，用于修改命令行参数 (Import sys module to modify command line arguments)
import os # 导入os模块，用于文件系统操作 (Import os module for file system operations)
import shutil # 导入shutil模块，用于高级文件操作 (Import shutil module for advanced file operations)
import torch # 导入torch库，main.py中会使用 (Import torch library, used in main.py)
import numpy # 导入numpy库，main.py中会使用 (Import numpy library, used in main.py)
import gymnasium # 导入gymnasium库，main.py中会使用 (Import gymnasium library, used in main.py)

# 清理之前的运行目录 (Clean up previous run directory if it exists)
run_dir_to_clean = "run_1" # 要清理的运行目录 (Run directory to clean)
if os.path.exists(run_dir_to_clean): # 如果目录存在 (If directory exists)
    print(f"Attempting to clean up existing directory: {run_dir_to_clean}") # 打印尝试清理目录的消息 (Print message about attempting to clean up directory)
    try: # 尝试 (Try)
        shutil.rmtree(run_dir_to_clean) # 删除目录树 (Remove directory tree)
        print(f"Successfully removed directory: {run_dir_to_clean}") # 打印成功删除目录的消息 (Print message about successfully removing directory)
    except Exception as e: # 捕获异常 (Catch exception)
        print(f"Warning: Failed to remove directory {run_dir_to_clean} using shutil.rmtree: {e}. Attempting os.system('rm -rf').") # 打印警告信息 (Print warning message)
        # 作为备用方案，尝试使用os.system (As a fallback, try using os.system)
        rm_command = f"rm -rf {run_dir_to_clean}" # 定义删除命令 (Define remove command)
        exit_code = os.system(rm_command) # 执行删除命令 (Execute remove command)
        if exit_code == 0: # 如果成功 (If successful)
            print(f"Successfully removed directory using os.system: {run_dir_to_clean}") # 打印成功删除信息 (Print success message)
        else: # 否则 (Otherwise)
            print(f"Warning: Failed to remove directory {run_dir_to_clean} using os.system with exit code {exit_code}. It might interfere with the test.") # 打印警告信息 (Print warning message)

# 模拟命令行参数 (Simulate command-line arguments)
sys.argv = [
    "main.py", # 脚本名称 (Script name)
    "--seed=0", # 随机种子 (Random seed)
    "--run_num=1", # 运行编号 (Run number)
    "--yaml_file=swimmer_forward", # YAML配置文件 (YAML configuration file)
    "--print_minimal=False", # 是否最小化打印 (Whether to minimize printing)
    "--num_aggregation_iters=1", # 聚合迭代次数 (Number of aggregation iterations)
    "--num_rollouts_train=2", # 训练用rollout数量 (Number of rollouts for training)
    "--num_rollouts_val=1", # 验证用rollout数量 (Number of rollouts for validation)
    "--steps_per_rollout_train=50", # 训练用rollout的每回合步数 (Steps per rollout for training)
    "--steps_per_rollout_val=50", # 验证用rollout的每回合步数 (Steps per rollout for validation)
    "--nEpoch=2", # 训练轮数 (Number of epochs for dynamics model training)
    "--num_trajectories_for_aggregation=2", # 用于聚合的轨迹数量 (Number of trajectories for aggregation)
    "--rollouts_forTraining=1", # 用于训练的rollout数量 (Number of rollouts for training in DAgger)
    "--num_rollouts_save_for_mf=1" # 为模型无关方法保存的rollout数量 (Number of rollouts to save for model-free method)
]

print(f"sys.argv set to: {sys.argv}") # 打印设置的sys.argv (Print the set sys.argv)

# 尝试导入并执行main.py的main函数 (Try to import and execute main.py's main function)
try: # 尝试 (Try)
    print("Attempting to import main function from main.py...") # 打印尝试导入信息 (Print attempt to import message)
    from main import main as main_function # 从main.py导入main函数 (Import main function from main.py)
    print("Successfully imported main function from main.py. Executing now...") # 打印成功导入信息 (Print success import message)
    main_function() # 执行main函数 (Execute main function)
    print("main_function from main.py executed successfully.") # 打印成功执行信息 (Print success execution message)
except SystemExit as e: # 捕获SystemExit异常 (Catch SystemExit exception)
    if e.code == 0: # 如果退出码为0 (If exit code is 0)
        print("main_function exited cleanly (sys.exit(0)).") # 打印干净退出信息 (Print clean exit message)
    else: # 否则 (Otherwise)
        print(f"main_function exited with sys.exit({e.code}).") # 打印退出码信息 (Print exit code message)
        # 重新引发异常以标记为失败 (Reraise to mark as failure for the agent)
        raise
except Exception as e: # 捕获其他所有异常 (Catch all other exceptions)
    import traceback # 导入traceback模块 (Import traceback module)
    print(f"An error occurred during import or execution of main.py: {e}") # 打印错误信息 (Print error message)
    print(traceback.format_exc()) # 打印完整的堆栈跟踪 (Print full stack trace)
    # 重新引发异常以标记为失败 (Reraise to mark as failure for the agent)
    raise
